CREATE TABLE series_selection
(
    series_selection_id    character varying(512)  NOT NULL,
    aidoc_site             character varying(256)  NOT NULL,
    research_reason        character varying(512)  NOT NULL,
    accession_number       character varying(256),
    aidoc_study_uid        character varying(1024) NOT NULL,
    aidoc_series_uid       character varying(1024) NOT NULL,
    series_storage_path    character varying(1024),
    series_selection_path  character varying(1024) NOT NULL,
    storage_type           character varying(256)  NOT NULL,
    anatomy                character varying(256)  NOT NULL,
    insertion_time_utc     character varying(256)  NOT NULL,
    study_date             character varying(256)  NOT NULL,
    study_description      character varying(512),
    series_description     character varying(512),
    protocol_name          character varying(256),
    manufacturer           character varying(256),
    ib_detected_anatomy    character varying(256),
    ib_anatomy_length      float,
    ib_anatomy_prediction  int,
    ib_detected_contrast   character varying(256),
    ib_contrast_prediction int,
    ib_prediction          int,
    analyst_email          character varying(256),
    series_local_path      character varying(1024),
    valid_to_analyze       character varying(64),
    patient_gender         character varying(64),
    aidoc_patient_age      character varying(64),
    aidoc_patient_id       character varying(256),
    plane                  character varying(64),
    patient_position       character varying(64),
    slice_thickness        character varying(256) NOT NULL,
    spacing_between_slices character varying(256) NOT NULL,
    number_of_slices       character varying(256) NOT NULL,
    field_of_view          character varying(256),
    pixel_spacing          character varying(256),
    kvp                    character varying(256) NOT NULL,
    convolution_kernel     character varying(256),
    calc_iter_recon_strength character varying(256),
    filter_type            character varying(64),
    exposure_time          character varying(256),
    exposure_modulation_type                    character varying(256),
    ctdivol                character varying(256),
    calc_spiral_pitch_factor                    character varying(256),
    calculated_effective_exposure_time_single_source            character varying(256),
    calc_effective_exposure_single_source_low   character varying(256),
    calc_effective_exposure_single_source_high  character varying(256),
    calc_normalized_noise_reference_single_source_low           character varying(256),
    calc_normalized_noise_reference_single_source_high          character varying(256),
    manufacturer_model_name                     character varying(256),
    number_of_pixel_rows                        character varying(256),
    number_of_pixel_columns                     character varying(256),
    calculated_kernel_type                      character varying(256),
    primary key (series_selection_id, aidoc_site, aidoc_series_uid)
);

CREATE TABLE image_based_tagging
(
    series_selection_id    character varying(512)  NOT NULL,
    aidoc_site             character varying(256)  NOT NULL,
    aidoc_series_uid       character varying(1024) NOT NULL,
    ai_project_name        character varying(256)  NOT NULL,
    insertion_time_utc     character varying(256)  NOT NULL,
    anatomy_ground_truth   character varying(256),
    contrast_ground_truth  character varying(256),
    raw_tagging            character varying(1024),
    interpreter_comments   character varying(2048),
    annotator_email        character varying(256),

    primary key (series_selection_id, aidoc_site, aidoc_series_uid)
);


