CREATE USER aidoc PASSWORD 'aidoc123' CREATEDB;
CREATE DATABASE data_metro WITH ENCODING='UTF8' OWNER=aidoc;

\connect data_metro

GRANT ALL PRIVILEGES ON database data_metro TO aidoc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO aidoc;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO aidoc;

