# Generated by Django 3.2 on 2021-04-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('poll', models.ForeignKey(db_column='poll_id', on_delete=django.db.models.deletion.CASCADE, to='api.poll')),
            ],
            options={
                'unique_together': {('poll', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('choice', models.ForeignKey(db_column='choice_id', on_delete=django.db.models.deletion.CASCADE, to='api.choice')),
                ('poll', models.ForeignKey(db_column='poll_id', on_delete=django.db.models.deletion.CASCADE, to='api.poll')),
            ],
            options={
                'unique_together': {('ip', 'poll')},
            },
        ),
    ]
