
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.food_table, name='food_table'),
    url(r'^home$', views.home, name='home'),
    url(r'^food_table/(\d+)/$', views.food_table, name='food_table'),
    url(r'^fast_view/(\d+)/$', views.fast_view, name='fast_view'),
    url(r'^random_image/(\d+)/$', views.random_image, name='random_image'),
    url(r'^dataset_view/([a-z0-9A-Z_]+)/$', views.dataset_view, name='dataset_view'),
    url(r'^(\d+)/$', views.food, name='food'),
    url(r'^add_food$', views.add_food, name='add_food'),
    url(r'^delete_food$', views.delete_food, name='delete_food'),
    url(r'^update_food_name$',    views.update_food_name,    name='update_food_name'),
    url(r'^update_food_symbol$',    views.update_food_symbol,    name='update_food_symbol'),
    url(r'^add_food_name$',    views.add_food_name,    name='add_food_name'),
    url(r'^delete_food_name$',    views.delete_food_name,    name='delete_food_name'),
    url(r'^add_food_ref$',    views.add_food_ref,    name='add_food_ref'),
    url(r'^add_or_edit_ref$',    views.add_or_edit_ref,    name='add_or_edit_ref'),
    url(r'^delete_food_ref$',    views.delete_food_ref,    name='delete_food_ref'),
    url(r'^go_to_food$', views.go_to_food, name='go_to_food'),
    url(r'^missing_nutrition$', views.missing_nutrition, name='missing_nutrition'),
    url(r'^missing_units$', views.missing_units, name='missing_units'),
    url(r'^missing_serving_size', views.missing_serving_size, name='missing_serving_size'),
    url(r'^update_nutrients$', views.update_nutrients, name='update_nutrients'),

    url(r'^flags$',    views.flags,    name='flags'),
    url(r'^repr_flags$',    views.repr_flags,    name='repr_flags'),
    url(r'^dataset/([^/]+)/(.*)$',    views.dataset,    name='dataset'),
    url(r'^thumbnail/([^/]+)/([^/]+)/(.*)$',    views.thumbnail,    name='thumbnail'),
    url(r'^add_food_comment$',    views.add_food_comment,    name='add_food_comment'),
    url(r'^update_food_comment$',    views.update_food_comment,    name='update_food_comment'),
    url(r'^delete_food_comment$',    views.delete_food_comment,    name='delete_food_comment'),


    url(r'^change_food_parent$', views.change_food_parent, name='change_food_parent'),
    url(r'^change_node_type$', views.change_node_type, name='change_node_type'),
    url(r'^add_secondary_ancestor$', views.add_secondary_ancestor, name='add_secondary_ancestor'),
    url(r'^del_secondary_ancestor$', views.del_secondary_ancestor, name='del_secondary_ancestor'),

    url(r'^move_category$', views.move_category, name='move_category'),
    url(r'^remove_category$', views.remove_category, name='move_category'),
    url(r'^change_component$', views.change_component, name='change_component'),
    url(r'^add_component$', views.add_component, name='add_component'),
    url(r'^update_liquid_loss$', views.update_liquid_loss, name='update_liquid_loss'),
    url(r'^remove_component$', views.remove_component, name='remove_component'),
    url(r'^change_ref$', views.change_ref, name='change_ref'),
    url(r'^remove_ref$', views.remove_ref, name='remove_ref'),
    url(r'^add_all_refs$', views.add_all_refs, name='add_all_refs'),
    url(r'^remove_all_refs$', views.remove_all_refs, name='remove_all_refs'),
    url(r'^ref_list$', views.ref_list, name='ref_list'),
    url(r'^unit_list$', views.unit_list, name='unit_list'),
    url(r'^unit_list_with_no_gram$', views.unit_list_with_no_gram, name='unit_list_with_no_gram'),
    url(r'^food_list$', views.food_list, name='food_list'),
    url(r'^database_list$', views.database_list, name='database_list'),
    url(r'^node_type_list$', views.node_type_list, name='node_type_list'),

    url(r'^get_food_component_of$', views.get_food_component_of, name='get_food_component_of'),
    url(r'^user_list$', views.user_list, name='user_list'),

    url(r'^nutrient_list$', views.nutrient_list, name='nutrient_list'),
    url(r'^attribute_list$', views.attribute_list, name='attribute_list'),

    url(r'^parent_list/(\d+)/$', views.parent_list, name='parent_list'),
    url(r'^component_list/(\d+)/$', views.component_list, name='component_list'),
    url(r'^change_weight$', views.change_weight, name='change_weight'),
    url(r'^remove_weight$', views.remove_weight, name='remove_weight'),

    url(r'^remove_is_countable', views.remove_is_countable, name='remove_is_countable'),
    url(r'^change_is_countable', views.change_is_countable, name='change_is_countable'),
    url(r'^remove_default_unit', views.remove_default_unit, name='remove_default_unit'),

    url(r'^change_cn$', views.change_cn, name='change_cn'),
    url(r'^remove_cn$', views.remove_cn, name='remove_cn'),
    url(r'^food_names_list/$', views.food_names, name='food_names_list'),
    url(r'^food_info_list/$', views.food_info_list, name='food_info_list'),
    url(r'^food_names_lookup/$', views.food_names_lookup, name='food_names_lookup'),
    url(r'^food_info/$', views.food_info, name='food_info'),
    url(r'^food_nutrition/$', views.food_nutrients, name='food_nutrients'),
    url(r'^descendants/$', views.descendants, name='descendants'),
    url(r'^food_weight/$', views.food_weight, name='food_weight'),
    url(r'^get_foods/$', views.get_foods, name='get_foods'),
    url(r'^food_hier/$', views.food_hier, name='food_hier'),
    #url(r'^foods_from_free_text$', views.foods_from_free_text, name='foods_from_free_text'),
    url(r'^analyze_food/$', views.analyze_food, name='analyze_food'),
    url(r'^foods_csv/$', views.foods_csv, name='foods_csv'),
    url(r'^foods_csv_serving/$', views.foods_csv_serving, name='foods_csv_serving'),
    url(r'^chinese_csv/$', views.chinese_csv, name='chinese_csv'),
    url(r'^foods_csv_classification/$', views.foods_csv_classification, name='foods_csv_classification'),
    url(r'^nlp_json$', views.nlp_json, name='nlp_jsons'),
    url(r'^change_food_attribute$', views.change_food_attribute, name='change_food_attribute'),
    url(r'^remove_food_attribute$', views.remove_food_attribute, name='remove_food_attribute'),
    url(r'^remove_food_amount_question', views.remove_food_amount_question, name='remove_food_amount_question'),
    url(r'^add_food_amount_question', views.add_food_amount_question, name='add_food_amount_question'),
    url(r'^remove_food_boolean_question', views.remove_food_boolean_question,name='remove_food_boolean_question'),
    url(r'^remove_choice_question', views.remove_food_choice_question, name='remove_food_choice_question'),
    url(r'^food_multiple_choice_question', views.food_choice_question, name='food_choice_question'),
    url(r'^food_questions', views.food_questions, name='food_questions'),
    url(r'^attribute_types', views.attribute_types, name='get_attributes'),
    url(r'^recipe', views.recipe, name='insert_recipe'),
    url(r'^nlp_recipe_component', views.nlp_recipe_component, name='nlp_recipe_component'),
    url(r'change_default_unit', views.change_default_unit, name='change_default_unit'),
    url(r'duplicate_names', views.duplicate_names, name='duplicate_names'),
    url(r'^search_usda$', views.search_usda, name='search_usda'),
    url(r'^get_nutrient', views.get_nutrient, name='get_nutrient'),

    url(r'^get_all_billfare_info$', views.get_all_billfare_info, name='getAllBillFareInfo'),
    url(r'^get_units$', views.get_units_view, name='get_units_view'),
    url(r'^billfare_info$', views.billfare_info, name='billFareInfo'),
    url(r'^nutrition_element_info$', views.nutrition_element_info, name='nutritionElementInfo'),
    url(r'^food_names_by_lang', views.food_names_by_lang, name='food_names_by_lang'),
    url(r'^statistics', views.statistics, name='statistics'),
    # url(r'^is_curated/(\d+)/$', views.is_curated, name='is_curated'),
    url(r'^hello$', views.hello, name='hello'),
    url(r'^food_attributes', views.food_attributes, name='food_attributes'),
    url(r'^category_portion_sizes_by_nutrient', views.category_portion_sizes_by_nutrient,
        name='category_portion_sizes_by_nutrient'),
    url(r'^category_portion_sizes', views.category_portion_sizes, name='category_portion_sizes'),
    url(r'^food_category_percentage/$', views.food_category_percentage, name='food_category_percentage'),
    url(r'^food_category_percentage_change/$', views.food_category_percentage_change, name='food_category_percentage_change'),
    url(r'^(\d+)/nutrition/$', views.food_nutrition, name='food_nutrition'),
    url(r'^(\d+)/descendants_by_attributes/$', views.food_descendants_by_attributes, name='descendants_by_attributes'),
    url(r'^(\d+)/descendants_by_attributes_any/$', views.food_descendants_by_attributes_any, name='descendants_by_attributes_any'),
    url(r'^activityLog', views.activityLog, name='activityLog'),
    url(r'^fooddb_queries/(\d+)/$', views.fooddb_queries, name='fooddb_queries'),
    url(r'^fooddb_queries/$', views.fooddb_queries, name='fooddb_queries'),
    url(r'^fooddb_filter/$', views.fooddb_filter, name='fooddb_filter'),
    url(r'^download_csv', views.download_csv, name='download_csv'),
    url(r'^grams_by_unit', views.grams_by_unit, name='grams_by_unit'),
    url(r'^api/nlp/names_list_to_food', views.names_list_to_food, name='names_list_to_food'),
    #url(r'^(\d+)/descendants/$', views.food_descendants, 'descendants'),
    url(r'^barcode_scanner$', views.barcode_scanner, name='barcode_scanner'),
    url(r'^activity_log_json', views.activity_log_json, name='activity_log_json'),
    url(r'^download_tree_directoris/(\d+)/', views.download_tree_directoris, name='download_tree_directoris'),
]

